// import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import ContextProvider from "@/components/commons/ContextProvider";
import { Navbar } from "@/components/nav-bar";
import { CartProvider } from "@/components/cart-provider";
import ChatBot from "@/components/commons/ChatBot";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";


// const roboto = Inter({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Market Place",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className="scroll-smooth overflow-x-hidden mt-8" suppressHydrationWarning>
        <body className= "flex min-h-screen flex-col justify between">
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} disableTransitionOnChange>
              <ContextProvider>
                <Navbar />
                <Toaster />
                <main className="flex-1 max-w-7xl mx-auto px-[10px] overflow-y-hidden">
                  {children}
                </main>
                <ChatBot />
                <Footer />
              </ContextProvider>
          </ThemeProvider>
        </body>
      </html>
  );
}